branch-defaults:
  dev:
    environment: springboot-env
    group_suffix: null
global:
  application_name: RandAPI
  branch: null
  default_ec2_keyname: null
  default_platform: Corretto 17
  default_region: us-west-2
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  repository: null
  sc: git
  workspace_type: Application
deploy:
  artifact: target/RandAPI-0.0.1-SNAPSHOT.jar
