branch-defaults:
  dev-fzq:
    environment: xiaopotato-env
deploy:
  artifact: target/xiao-potato-0.0.1-SNAPSHOT.jar
environment-defaults:
  potato-env:
    branch: null
    repository: null
global:
  application_name: xiaoPotato
  default_ec2_keyname: null
  default_platform: Corretto 17
  default_region: us-west-2
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  sc: git
  workspace_type: Application
