name: Deploy Spring Boot Application

on:
  push:
    branches:
      - main  # Trigger when merging to the main branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Check out the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Java environment
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'

      # Set up Maven cache
      - name: Cache Maven dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven

      # Build the application
      - name: Build with Maven
        run: mvn clean package -DskipTests

      # Deploy to server using SSH and password
      - name: Deploy to Server
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{ secrets.POTATO_HOST }}           # Server hostname or IP
          username: ${{ secrets.POTATO_USER }}       # SSH username
          password: ${{ secrets.POTATO_KEY }}        # SSH password stored in secrets
          port: 22                                   # Default SSH port, change if needed
          script: |
            # Stop old application
            screen -S springboot-app -X quit || true
            
            # Export Aliyun OSS credentials as environment variables
            echo "Exporting Aliyun OSS credentials..."
            export ALIYUN_ACCESS_KEY_ID=${{ secrets.ALIYUN_ACCESS_KEY_ID }}
            export ALIYUN_ACCESS_KEY_SECRET=${{ secrets.ALIYUN_ACCESS_KEY_SECRET }}
            echo "Aliyun credentials exported."
            
            # Start new application
            screen -dmS springboot-app
            screen -S springboot-app -X stuff 'java -Dspring.profiles.active=prod \
              -Daliyun.accessKeyId=${ALIYUN_ACCESS_KEY_ID} \
              -Daliyun.accessKeySecret=${ALIYUN_ACCESS_KEY_SECRET} \
              -jar xiao-potato-0.0.1-SNAPSHOT.jar\n'
            
            # exit current screen session
            sleep 2
            screen -S springboot-app -X stuff $'\003'
