name: Deploy Spring Boot Application

on:
  push:
    branches:
      - main  # Trigger when merging到main分支时触发

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Check out the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Java environment
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'

      # Set up Maven cache
      - name: Cache Maven dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven

      # Build the application
      - name: Build with Maven
        run: |
          echo "Running Maven build..."
          mvn clean package -DskipTests
          if [ $? -ne 0 ]; then
            echo "Maven build failed!"
            exit 1
          fi
          echo "Maven build completed successfully."

          # Check if target directory exists and contains the JAR file
          echo "Checking for generated JAR file..."
          if [ -d target ] && [ -f target/xiao-potato-0.0.1-SNAPSHOT.jar ]; then
            echo "Build successful: JAR file found in target directory."
          else
            echo "Build failed: JAR file not found in target directory!"
            exit 1
          fi


      - name: Verify JAR file existence
        run: |
          echo "Verifying JAR file..."
          ls -l ${{ github.workspace }}/target
          FULL_PATH="${{ github.workspace }}/target/xiao-potato-0.0.1-SNAPSHOT.jar"
          echo "Expected JAR file full path: $FULL_PATH"
          if [ ! -f $FULL_PATH ]; then
            echo "Error: JAR file not found in target directory!"
            exit 1
          fi
          echo "JAR file is present at: $FULL_PATH"
      

      # Deploy to server using SSH and password
      - name: Set Full Path for JAR File
        id: jar_path
        run: |
          echo "JAR_FILE_PATH=${{ github.workspace }}/target/xiao-potato-0.0.1-SNAPSHOT.jar" >> $GITHUB_ENV
          echo "JAR_FILE_PATH set to: ${{ github.workspace }}/target/xiao-potato-0.0.1-SNAPSHOT.jar"

      - name: Deploy to Server
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{ secrets.POTATO_HOST }}
          username: ${{ secrets.POTATO_USER }}
          password: ${{ secrets.POTATO_KEY }}
          port: 22
          script_stop: true
          script: |
            # Remove old JAR
            rm -f ~/xiao-potato-0.0.1-SNAPSHOT.jar
            screen -S springboot-app -X quit || true
            sleep 30
            # Stop existing application
            PID=$(lsof -t -i:8081 || true)
            if [ ! -z "$PID" ]; then
              kill -9 $PID || true
            fi
            # Create startup script
            cat > /tmp/start-app.sh << 'EOF'
            #!/bin/bash
            export ALIYUN_ACCESS_KEY_ID=${{ secrets.ALIYUN_ACCESS_KEY_ID }}
            export ALIYUN_ACCESS_KEY_SECRET=${{ secrets.ALIYUN_ACCESS_KEY_SECRET }}
            java -Dspring.profiles.active=prod \
                 -Daliyun.accessKeyId=$ALIYUN_ACCESS_KEY_ID \
                 -Daliyun.accessKeySecret=$ALIYUN_ACCESS_KEY_SECRET \
                 -jar ~/xiao-potato-0.0.1-SNAPSHOT.jar
            EOF
            chmod +x /tmp/start-app.sh

      # File transfer step
      - name: Transfer JAR
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.POTATO_HOST }}
          username: ${{ secrets.POTATO_USER }}
          password: ${{ secrets.POTATO_KEY }}
          source: "target/xiao-potato-0.0.1-SNAPSHOT.jar"
          target: "~"
          strip_components: 1
          timeout: 300s

      # Verify transfer
      - name: Verify Transfer
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{ secrets.POTATO_HOST }}
          username: ${{ secrets.POTATO_USER }}
          password: ${{ secrets.POTATO_KEY }}
          script: |
            while [ ! -f ~/xiao-potato-0.0.1-SNAPSHOT.jar ]; do
              echo "Waiting for JAR file..."
              sleep 5
            done
            echo "Transfer verified"

      # Add final step to start application
      - name: Start Application
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{ secrets.POTATO_HOST }}
          username: ${{ secrets.POTATO_USER }}
          password: ${{ secrets.POTATO_KEY }}
          port: 22
          script: |
            screen -dmS springboot-app /tmp/start-app.sh
